#development version of configurations
server:
  port: 8083

# DataBase connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: auth_user
    password: ezpzlemonsqz@123
    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      pool-name: HikariCCP
#      maximum-pool-size: 5
#      connection-timeout: 10000
#      idle-timeout: 600000
#      max-lifetime: 1800000
#      validation-timeout: 5000
#      leak-detection-threshold: 0
#      initialization-fail-timeout: -1

# jpa and hibernate configurations
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true